ui_tests_directory := justfile_directory()

test-all:
    @just test bat-gnu

clean-all:
    @just clean bat-gnu

with-home directory +command:
    HOME='{{ ui_tests_directory }}/{{ directory }}' \
    XDG_BIN_HOME='{{ ui_tests_directory }}/{{ directory }}/executables' \
    XDG_CACHE_HOME='{{ ui_tests_directory }}/{{ directory }}/cache' \
    XDG_CONFIG_HOME='{{ ui_tests_directory }}/{{ directory }}/configuration' \
    XDG_DATA_HOME='{{ ui_tests_directory }}/{{ directory }}/data' \
    XDG_STATE_HOME='{{ ui_tests_directory }}/{{ directory }}/state' \
    {{ command }}

test directory:
    cargo build

    @just with-home '{{ directory }}' \
    '{{ ui_tests_directory }}/../target/debug/package-manager' install

    ! test -d '{{ ui_tests_directory }}/{{ directory }}/.local'

clean directory:
    rm -rf "{{ ui_tests_directory }}/{{ directory }}/executables"
    rm -rf "{{ ui_tests_directory }}/{{ directory }}/cache"
    rm -rf "{{ ui_tests_directory }}/{{ directory }}/data"
    rm -rf "{{ ui_tests_directory }}/{{ directory }}/state"
