name = "glibc"
author = "gnu"

[provides]
libc = "6"
libm = "6"

[download]

[download.tarball_index]
url = "https://ftpmirror.gnu.org/gnu/glibc/"
version.exact = "2.43"
file_name_prefix = "glibc-"

[build]
directory = "glibc-2.43"
system = "configure_make"
configure_flags = ["--disable-sanity-checks", "--disable-werror"]
